version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
      - "./conf/mysql:/etc/mysql/conf.d"
    restart: always    
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: materliu
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest    
    links:
      - db
    ports:
      - "9097:80"
    restart: always    
    environment: 
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_USER: materliu
      WORDPRESS_DB_NAME: wordpress  

